resource.AddFile( "img/player.png" )
resource.AddFile( "img/heart.png" )
resource.AddFile( "img/shield.png" )
resource.AddFile( "img/pistol.png" )
resource.AddFile( "img/ammo_1.png" )
resource.AddFile( "img/ammo_2.png" )
